abreviacoes = {
    # Tratamentos
    "Sr.": "Senhor",
    "Sra.": "Senhora",
    "Srª": "Senhora",
    "Sr": "Senhor",
    "Sra": "Senhora",
    "Dr.": "Doutor",
    "Dra.": "Doutora",
    "Dr": "Doutor",
    "Dra": "Doutora",
    "Prof.": "Professor",
    "Prof": "Professor",
    "Profa.": "Professora",
    "Profa": "Professora",
    
    # Endereços
    "Av.": "Avenida",
    "Av": "Avenida",
    "R.": "Rua",
    "R": "Rua",
    "Rod.": "Rodovia",
    "Rod": "Rodovia",
    "Est.": "Estrada",
    "Est": "Estrada",
    "Trav.": "Travessa",
    "Trav": "Travessa",
    "Al.": "Alameda",
    "Al": "Alameda",
    "Lgo.": "Largo",
    "Lgo": "Largo",

    # Datas e outros
    "a.C.": "antes de Cristo",
    "d.C.": "depois de Cristo",
    "etc.": "êti cétera",
    "etc": "êti cétera",
    "e.g.": "por exemplo",
    "i.e.": "isto é",
    "vs.": "versus",
    "nº": "número",
    "Nº": "número",
    "no.": "número",
    "a.m.": "antes do meio-dia",
    "p.m.": "depois do meio-dia",

    # Estados brasileiros (UF → nome por extenso)
    "AC": "Acre",
    "AL": "Alagoas",
    "AP": "Amapá",
    "AM": "Amazonas",
    "BA": "Bahia",
    "CE": "Ceará",
    "DF": "Distrito Federal",
    "ES": "Espírito Santo",
    "GO": "Goiás",
    "MA": "Maranhão",
    "MT": "Mato Grosso",
    "MS": "Mato Grosso do Sul",
    "MG": "Minas Gerais",
    "PA": "Pará",
    "PB": "Paraíba",
    "PR": "Paraná",
    "PE": "Pernambuco",
    "PI": "Piauí",
    "RJ": "Rio de Janeiro",
    "RN": "Rio Grande do Norte",
    "RS": "Rio Grande do Sul",
    "RO": "Rondônia",
    "RR": "Roraima",
    "SC": "Santa Catarina",
    "SP": "São Paulo",
    "SE": "Sergipe",
    "TO": "Tocantins",

    # Unidades e Medidas
    "kg": "quilos",
    "km/h": "quilômetros por hora",
    "Km/h": "quilômetros por hora",
    "Km": "quilômetros",
    "km": "quilômetros",
    "m": "metros",
    "h": "horas",
    "s": "segundos",
    "cm": "centímetros",
    "mm": "milímetros",
    "ml": "mililitros",
    "l": "litros",
    "m²": "metros quadrados",
    "°C": "graus celsius",
    "°C":"graus celsius",
    "%": "por cento",
    "R$": "reais",
    "USD": "dólares",
    "U$": "dólares"
}